# Generated by Django 5.1 on 2024-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.CharField(blank=True, help_text="A hex code representing the user's color.", max_length=7, null=True),
        ),
    ]
