# Generated by Django 5.1 on 2024-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_user_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="The user's phone number.", max_length=15, null=True),
        ),
    ]
